name: IRIS ML Pipeline
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  
jobs:
  test-and-report:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run training pipeline
        run: python train.py

      - name: Run validation tests
        run: |
          pytest test_iris_validation.py --junitxml=test-results.xml --html=test-report.html

      - name: Generate CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create comprehensive report
          echo "# IRIS Pipeline Test Results" > report.md
          echo "" >> report.md
          # ...rest of your script...
          cml comment create report.md

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.xml
            test-report.html
            artifacts/


        
